---
title             : "Implicit Association Tests: Stimuli Validation from Participant Responses"
shorttitle        : "IAT: Stimuli Validation"

author: 
  - name          : "S. A. M. Hogenboom"
    affiliation   : "1,3"
    corresponding : yes    # Define only one corresponding author
    email         : "sally.hogenboom@gmail.com"
    address       : ""
    role:         # Contributorship roles (e.g., CRediT, https://casrai.org/credit/)
      - Conceptualization
      - Formal Analysis
      - Methodology
      - Validation
      - Visualization
      - Writing – original draft
      - Writing – review & editing
  - name          : "K. Schulz"
    affiliation   : "1"
    corresponding : no    # Define only one corresponding author
    email         : ""
    address       : ""
    role:         # Contributorship roles (e.g., CRediT, https://casrai.org/credit/)
      - Conceptualization
      - Funding acquisition
      - Supervision
      - Writing – review & editing
  - name          : "L. van Maanen"
    affiliation   : "2"
    corresponding : no    # Define only one corresponding author
    email         : ""
    role:         # Contributorship roles (e.g., CRediT, https://casrai.org/credit/)
      - Conceptualization
      - Methodology
      - Supervision
      - Validation
      - Visualization
      - Writing – review & editing
affiliation:
  - id            : "1"
    institution   : "Institute for Logic, Language and Computation, University of Amsterdam, The Netherlands"
  - id            : "2"
    institution   : "Department of Experimental Psychology, Utrecht University, The Netherlands"
  - id            : "3"
    institution   : "Faculty of Psychology, Methodology & Statistics, Open Universiteit Nederland, The Netherlands"

authornote: |
  This publication is part of the project "The biased reality of online media - Using stereotypes to make media manipulation visible" (with project number 406.DI.19.059) of the research programme Open Competition Digitalisation-SSH which is financed by the Dutch Research Council (NWO). We further want to acknowledge that this research would not be possible without the research efforts and open data policies of Project Implicit ([https://www.projectimplicit.net/](https://www.projectimplicit.net/)).

abstract: |
  The Implicit Association Test [IAT, @GREENWALD1998] is a popular instrument for measuring attitudes and (stereotypical) biases. @GREENWALD2021 proposed a concrete method for validating IAT stimuli: appropriate stimuli should be familiar and easy to classify – translating to rapid (response times < 800 ms) and accurate (error < 10%) participant responses. We conducted three analyses to explore the theoretical and practical utility of these proposed validation criteria. We first applied the proposed validation criteria to the data of 15 IATs that were available via Project Implicit. A bootstrap approach with 10,000 ‘experiments’ of 100 participants showed that 5.85 % of stimuli were reliably valid: we are more than 95% confident that a stimulus will also be valid in a new sample of 18-25 year old US participants. Most stimuli (78.44%) could not be reliably validated, indicating a less than 5% certainty in the outcome of stimulus (in)validity for a new sample of participants. We then explored how stimulus validity differs across IATs. Results show that only some stimuli are consistently (in)valid. Most stimuli show between-IAT variances which indicate that stimulus validity differs across IAT contexts. In the final analysis we explored the effect of stimulus type (images; nouns; names; adjectives) on stimulus validity. Stimulus type was a significant predictor of stimulus validity. Although images attain the highest stimulus validity, raw data shows large differences within stimulus types. Together the results indicate a need for revised validation criteria. We finish with practical recommendations for stimulus selection and (post-hoc) stimulus validation.
  
keywords          : "Implicit Association Test, Internal Validity"
wordcount         : "12,962"

# Add bibtext bibliographies. Managed with Zotero
# literature.bib; all citations in text
# r-references.bib; all used R-packages, cited in footnote
# Import custom bibtex bibliographies
bibliography      : ["bibliographies/literature.bib", "bibliographies/r-references.bib"]

floatsintext      : yes
linenumbers       : no
draft             : no
mask              : no

figurelist        : no
tablelist         : no
footnotelist      : no

classoption       : "man"
output            : 
  papaja::apa6_docx:
    # SOURCE: https://github.com/crsh/papaja
    # MANUAL: http://frederikaust.com/papaja_man/
      # When referring to sections use their numbers rather than their names
      # Allow figure captions
      # Custom styles applied to the docx document.
      # numbered headers in accordance with apa guidelines
      # number figures and attach captions
      number_sections: TRUE
      # Adapted from: https://github.com/crsh/papaja/blob/master/inst/rmarkdown/templates/apa6/resources/apa6_man.docx
      reference_docx: "style_templates/apa7.docx"
      reference_num: TRUE
      fig_caption: TRUE

# SOURCE: https://www.zotero.org/styles
csl: "style_templates/apa-single-spaced.csl"
link-citations: true
header-includes:
  - \raggedbottom # allow empty space on bottom of pages
  - \usepackage{float} # use the 'float' package
  - \floatplacement{figure}{H} # make every figure with caption = h = exact placement
---

<!---
###############################################################################
###############################################################################
### This code was produced by:                                             ###
### The BIAS Barometer Team (https://bias-barometer.github.io/)            ###
### Institute for Logic, Language and Computation                          ###
### University of Amsterdam                                                ###
### Science Park 107                                                       ###
### 1098 XG Amsterdam                                                      ###
### The Netherlands                                                        ###
###                                                                        ###
### CORRESPONDENCE: sally.hogenboom@gmail.com                              ###
###                                                                        ###
### LICENSE:                                                               ###
### This code is available under a CC BY-NC-SA 4.0 license                 ###
### https://creativecommons.org/licenses/by-nc-sa/4.0/                     ###
###                                                                        ###
### BY  – Credit must be given to the creator                              ###
### NC  – Only noncommercial uses of the work are permitted                ###
### SA  – Adaptations must be shared under the same terms                  ###
###############################################################################
###############################################################################
--->

```{r setup, include = FALSE, cache = FALSE}
# Seed for random number generation so that results can be replicated
set.seed(18)

#### PACKAGES ####
# APA Styling for the Manuscript
library("papaja") 
# Other styling of the Manuscript
library("officer")
library("officedown")
library("bookdown")

# Package Citations
# Create reference list for all installed packages
# File was manually added to retain only the packages relevant for this project
my_citations <- 
    papaja::cite_r(
  file = here::here("bibliographies", 
                    "r-references.bib"),
  footnote = TRUE # include as footnote when included 
)

# Add extra space, otherwise the brackets are not converted to (...)
my_citations$r <- gsub(my_citations$r, pattern = "[^", replacement = " [^",
                       fixed = TRUE)

#### KNITTING ####
# Options that determine the output of the document - PER CHUNK
knitr::opts_chunk$set(echo = FALSE, # do not include code
                      include = FALSE, # do not include code
                      cache = TRUE, # save computations
                      cache.comments = FALSE, # do not discard cache if comments
                      # ... change
                      # Default figure width as width of A4 page
                      fig.width = (16 / 2.54) # 16 cm (A4 - margins) -> inches
                      )

# GLOBAL Options
options(
  # Suppress summarize warning info from the dplyr package
  dplyr.summarise.inform = FALSE,
  # Duplicate labels arise when using child documents in the Appendix
  knitr.duplicate.label = "allow",
  # Increase the timeout duration to allow downloading large files (e.g., GBs for Race IAT)
  timeout = 10000)

# Style the output of numbers in text to have comma's 
# ... as the big number separators (e.g., 1,000)
knitr::knit_hooks$set(inline = function(x) {
  prettyNum(x, big.mark = ",", decimal.mark = ".")
})

#### CUSTOM FUNCTIONS ####
# Load custom created functions (e.g., exclusion criteria)
invisible(
  # do NOT print which functions have been loaded
  # Loop over all found files
  sapply(
    list.files(
      here::here("functions"),
                    pattern = ".R",
      recursive = TRUE),
         FUN = function(x) {
           # Run the code == load function into global memory
           source(file = here::here("functions", x))
           })
  )

#### STUDY PARAMETERS ####
# Add here so that they can be referred to in the text
# Number of times a sample is created (for bootstrapping analysis)
n_samples <- 10000
# Number of participants per sample
n_subjects_per_sample <- 100
# Year from which the data should be downloaded (full sample)
year_of_interest <- 2020
# Months from which the data should be downloaded (full sample)
months_of_interest <- c(11) # November
# Included IATs
included_IATs <- 
  c("Age", "Arab", "Asian-American", "Disability", 
    "Gender-Career", "Gender-Science",
    "Native-American", "President", "Race",
    "Religion", "Sexuality", "Skin-Tone",
    "Transgender", "Weapons", "Weight")
```

# Introduction

```{r child = "chapters/introduction.Rmd"}
```

# Methods

```{r, child = "chapters/methods-intro.Rmd"}
```

## Data {#methods-data}
```{r, child = "chapters/methods-data.Rmd"}
```

## Exclusion Criteria {#methods-exclusion}
```{r, child = "chapters/methods-exclusion.Rmd"}
```

## Analysis Plan {#methods-analyses}
```{r, child = "chapters/methods-analyses.Rmd"}
```

# Results

## Pilot {#results-pilot}

```{r, child = "chapters/results-pilot.Rmd"}
```

## Full Sample Results {#results-full}

```{r, child = "chapters/results-full.Rmd"}
```

# Discussion {#discussion}

```{r, child = "chapters/discussion.Rmd"}
```

\newpage
# References {-}

<!-- automatically adds the used references from the bibliographies here -->
<div id="refs"></div>

\newpage
# Appendices {-}

## Appendix A {#IAT-Appendix}
```{r, child = "chapters/appendix-IAT-paradigm.Rmd"}
```

<!-- ONLINE APPENDIX -->

```{r, eval = FALSE}
# NOTE: run code rather than knit. Otherwise the documents cannot be rendered.

#### GENERATE PLOTS ####
# Similar to chapters/results-pilot
# Output size changes because the number of stimuli per IAT varies greatly. 
# The largest plots are those which include the adjective stimuli.

for (IAT in included_IATs) {
  # Create plot if it doesn't yet exist
  if(!file.exists(here::here("plots", "IATs", glue::glue("{IAT}_{year_of_interest}.png")))) {
    
    if (IAT %in% c("Age",
                 "Arab",
                 "Disability",
                 "Race",
                 "Religion",
                 "Sexuality",
                 "Skin-Tone",
                 "Weight")) {
    # IATs with a large range of stimuli 
    # ... (e.g., positive/negative) 
    # ... which require more plotting space.
    plotHeight <- 50
  } else if (IAT %in% c("Gender-Career",
                        "Asian-American",
                        "Gender-Science",
                 "Native-American",
                 "Transgender",
                 "Weapons")) {
    plotHeight <- 19.5
  } else if (IAT %in% c("President")) {
    plotHeight <- 100
  }
  
#### PLOTS ####
results_plot(IAT,
             year_of_interest,
             plotHeight)
    
  } # END if plot exists
  
} # END IAT LOOP

#### RENDER OUTPUT FILES ####
# Generate a results report per IAT

dir.create("IAT_results", showWarnings = FALSE)

for (IAT in included_IATs) {
  rmarkdown::render(
    here::here("chapters",
               "appendix-IAT-results.Rmd"),
    params = list(
      IAT_name = IAT
    ),
    output_file = 
      glue::glue(
        here::here("IAT_results",
                   "{IAT}_{year_of_interest}.html")
  ))
}
```
