---
editor_options: 
  chunk_output_type: console
---
<!--
################################################################################
################################################################################
### LICENSE:                                                                 ###
### This code is available under a CC BY-NC-SA 4.0 license                   ###
### https://creativecommons.org/licenses/by-nc-sa/4.0/                       ###
###                                                                          ###
### BY  – Credit must be given to the creator                                ###
### NC  – Only noncommercial uses of the work are permitted                  ###
### SA  – Adaptations must be shared under the same terms                    ###
################################################################################
################################################################################
-->

<!-- OSF guidelines:
"Full description of proposed sample characteristics, including criteria for data inclusion and exclusion (e.g. outlier extraction). Procedures for objectively defining exclusion criteria due to technical errors or for any other reasons must be specified, including details of how and under what conditions data would be replaced." -->

We prepared our manuscript with `RMarkdown` in `r my_citations$r` which had several benefits. First, we reduced research degrees of freedom [@WICHERTS2016] by formalizing data preprocessing and exclusion (section \@ref(methods-exclusion)), the analyses (section \@ref(methods-analyses)), and to some extent the results (section \@ref(results-pilot)). We conducted pilot analyses (section \@ref(methods-data)) which we used to optimize all code. The pilot code was not capable of (1) downloading data directly from the Open Science Framework, (2) dealing with larger datasets, and (3) visualizing the final results in a comprehensive manner. We therefore updated the code while keeping track of all changes with `git` version control. The changes were also documented in an [explanation of changes](https://osf.io/dw23y/?view_only=25b62f307a1349e7883549b473091483), allowing anyone to track and verify (the need for) the changes we made between Stage 1 and Stage 2.

A second benefit to preparing and publishing our analyses in `R` is fostering Open Science. Researchers can easily replicate the analyses on new data sets, use different (model) parameters, and expand with additional analyses or visualizations. All scripts are available via the Open Science Framework (OSF; https://osf.io/dw23y/?view_only=25b62f307a1349e7883549b473091483) which is connected to a Github repository (*removed for review purposes*). Please see the *workflow* vignette for a practical summary.

In section \@ref(methods-data) we first discuss the origin and nature of the data. We also describe the differences between the pilot data and the full data set. In section \@ref(methods-exclusion) we describe the exclusion criteria and how each of them affected the data with which we worked. We then describe in section \@ref(methods-analyses) the analyses: how we computed the (reliability) of the validation criteria and compared stimulus validity across IATs and stimulus types. The full research plan was approved by the Ethics Review Board at the *name removed for review purposes* [^ethics].

[^ethics]: The Ethics Review Board of *name removed for review purposes* approved the research plan on 19th of March 2021 (ref: *removed for review purposes*).

<!-- include the used packages as a footnote -->
`r my_citations$pkgs`
